# Configuration file

# Publish all joint states ...
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position controllers ...
# For each joint we have to define a joint position controller
# Type of JointPositionController comes from effort_controllers
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: l00__l01
  pid: {p: 700.00, i: 50, d: 70.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: l01__l02
  pid: {p: 700.00, i: 50, d: 70.0}